import { getDatabase } from '@/db';
import { id, json, now, requireSession } from '@/lib/server';

const text=(row:any,key:string)=>String(row?.[key]||'').trim();
const category=(value:string)=>['common','general','career','convergence'].includes(value)?value:'';
export async function POST(request:Request){
 const session=await requireSession(request,'admin');const body=await request.json() as any;const db=getDatabase();const time=now();const academicYear=Number(body.academicYear);const entryYear=Number(body.entryYear);const rows=(Array.isArray(body.rows)?body.rows:[]).map((row:any,index:number)=>({...row,rowNumber:index+1,subjectName:text(row,'subjectName')}));
 if(body.action==='updateEntry'){
  const entry=body.entry||{}; const entryId=text(entry,'id'); if(!entryId)return json({error:'수정할 과목을 찾지 못했습니다.'},{status:400});
  const active=await db.prepare('SELECT sb.id FROM school_course_book_entries sb JOIN reference_uploads ru ON ru.id=sb.upload_id WHERE sb.id=? AND ru.active=1').bind(entryId).first();
  if(!active)return json({error:'현재 적용 중인 학교 안내 과목만 수정할 수 있습니다.'},{status:404});
  const subjectName=text(entry,'subject_name'); if(!subjectName)return json({error:'과목명을 입력해주세요.'},{status:400});
  await db.prepare('UPDATE school_course_book_entries SET subject_group=?,subject_name=?,curriculum_category=?,school_requirement=?,selection_group=?,selection_count=?,credit=?,timing=?,selection_conditions=?,concurrent_limit=?,prerequisite=?,subsequent=?,csat_priority=?,humanities_priority=?,science_priority=?,admin_note=?,updated_at=? WHERE id=?').bind(text(entry,'subject_group'),subjectName,text(entry,'curriculum_category'),entry.school_requirement==='required'?'required':'optional',text(entry,'selection_group'),text(entry,'selection_count'),text(entry,'credit'),text(entry,'timing'),text(entry,'selection_conditions'),text(entry,'concurrent_limit'),text(entry,'prerequisite'),text(entry,'subsequent'),entry.csat_priority?1:0,entry.humanities_priority?1:0,entry.science_priority?1:0,text(entry,'admin_note'),time,entryId).run();
  await db.prepare('INSERT INTO audit_logs(id,actor,action,entrance_year,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),session.actor,'학교 수강신청 책자 과목 수정',Number(entry.entry_year)||null,JSON.stringify({entryId,subjectName}),time).run();
  return json({ok:true});
 }
 if(body.action==='bulkFlags'){
  const ids=(Array.isArray(body.entryIds)?body.entryIds:[]).map((value:any)=>String(value)).filter(Boolean); const field=text(body,'field'); const allowed=new Set(['csat_priority','humanities_priority','science_priority']); if(!ids.length||!allowed.has(field))return json({error:'일괄 변경할 과목과 항목을 선택해주세요.'},{status:400});
  const placeholders=ids.map(()=>'?').join(','); const active=await db.prepare(`SELECT sb.id FROM school_course_book_entries sb JOIN reference_uploads ru ON ru.id=sb.upload_id WHERE ru.active=1 AND sb.id IN (${placeholders})`).bind(...ids).all(); const validIds=(active.results||[]).map((row:any)=>row.id); if(!validIds.length)return json({error:'현재 적용 중인 과목을 찾지 못했습니다.'},{status:404});
  const validPlaceholders=validIds.map(()=>'?').join(','); await db.prepare(`UPDATE school_course_book_entries SET ${field}=?,updated_at=? WHERE id IN (${validPlaceholders})`).bind(body.enabled?1:0,time,...validIds).run();
  await db.prepare('INSERT INTO audit_logs(id,actor,action,details_json,created_at) VALUES(?,?,?,?,?)').bind(id('audit'),session.actor,'학교 수강신청 책자 과목 일괄 수정',JSON.stringify({field,enabled:!!body.enabled,count:validIds.length}),time).run();
  return json({ok:true,count:validIds.length});
 }
 if(!academicYear||!entryYear)return json({error:'기준학년도와 대상 입학년도를 입력해주세요.'},{status:400});
 const existing=await db.prepare('SELECT id,file_name,row_count FROM reference_uploads WHERE reference_type=? AND criteria_year=? AND active=1').bind('school_book',academicYear).all();const invalid=rows.filter((row:any)=>!row.subjectName);const valid=rows.filter((row:any)=>row.subjectName);
 const summary={totalCount:rows.length,validCount:valid.length,errorCount:invalid.length,sample:valid.slice(0,10)};
 if(body.action==='preview')return json({summary,invalidRows:invalid.slice(0,20),existing:existing.results||[]});
 if(body.action!=='commit')return json({error:'지원하지 않는 작업입니다.'},{status:400});
 const replaceIds=new Set(Array.isArray(body.replaceUploadIds)?body.replaceUploadIds:[]);const active=(existing.results||[]) as any[];if(active.some(item=>!replaceIds.has(item.id)))return json({error:'기존 학교 수강신청 책자가 있습니다. 교체 여부를 확인해주세요.'},{status:409});
 const uploadId=id('school_book');const statements:D1PreparedStatement[]=[];for(const item of active.filter(item=>replaceIds.has(item.id)))statements.push(db.prepare('UPDATE reference_uploads SET active=0 WHERE id=?').bind(item.id));
 statements.push(db.prepare('INSERT INTO reference_uploads(id,reference_type,criteria_year,file_name,uploaded_by,row_count,failed_count,active,replaced_upload_id,summary_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(uploadId,'school_book',academicYear,text(body,'fileName')||'학교 수강신청 안내',session.actor,valid.length,invalid.length,1,active[0]?.id||null,JSON.stringify(summary),time));
 for(const row of valid){const grade=[2,3].includes(Number(row.targetGrade))?Number(row.targetGrade):null;const semester=[1,2].includes(Number(row.targetSemester))?Number(row.targetSemester):null;const offered=grade&&semester?1:0;const schoolRequirement=row.schoolRequirement==='required'?'required':'optional';statements.push(db.prepare('INSERT INTO school_course_book_entries(id,upload_id,academic_year,entry_year,current_grade,target_grade,target_semester,subject_group,subject_name,curriculum_category,school_requirement,selection_group,selection_count,credit,timing,selection_conditions,concurrent_limit,prerequisite,subsequent,csat_priority,humanities_priority,science_priority,source_location,admin_note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id('school_book_row'),uploadId,academicYear,entryYear,Number(row.currentGrade)||null,grade,semester,text(row,'subjectGroup'),row.subjectName,category(text(row,'curriculumCategory'))||text(row,'curriculumCategory'),schoolRequirement,text(row,'selectionGroup'),text(row,'selectionCount'),text(row,'credit'),text(row,'timing'),text(row,'selectionConditions'),text(row,'concurrentLimit'),text(row,'prerequisite'),text(row,'subsequent'),row.csatPriority?1:0,row.humanitiesPriority?1:0,row.sciencePriority?1:0,text(row,'sourceLocation'),text(row,'adminNote'),time,time));if(offered)statements.push(db.prepare('INSERT INTO curricula(id,entrance_year,target_grade,target_semester,area,course_name,selection_type,offered,note,source_upload_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(entrance_year,target_grade,target_semester,course_name) DO UPDATE SET area=excluded.area,selection_type=excluded.selection_type,offered=excluded.offered,note=excluded.note,source_upload_id=excluded.source_upload_id,updated_at=excluded.updated_at').bind(id('curriculum'),entryYear,grade,semester,text(row,'subjectGroup'),row.subjectName,category(text(row,'curriculumCategory'))||'general',1,text(row,'adminNote'),uploadId,time,time));}
 statements.push(db.prepare('INSERT INTO audit_logs(id,actor,action,entrance_year,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),session.actor,'학교 수강신청 책자 저장',entryYear,JSON.stringify({academicYear,fileName:text(body,'fileName'),count:valid.length}),time));await db.batch(statements);return json({ok:true,savedCount:valid.length,failedCount:invalid.length});
}
