import JSZip from 'jszip';

export type SchoolBookRow={subjectName:string;subjectGroup:string;curriculumCategory:string;schoolRequirement:string;targetGrade:string;targetSemester:string;selectionGroup:string;selectionCount:string;credit:string;timing:string;selectionConditions:string;concurrentLimit:string;prerequisite:string;subsequent:string;sourceLocation:string;adminNote:string;csatPriority:boolean;humanitiesPriority:boolean;sciencePriority:boolean};
const clean=(value:string)=>value.replace(/[\r\n]+/g,' ').replace(/\s+/g,' ').trim();
const key=(value:string)=>clean(value).replace(/[·ㆍ]/g,'').replace(/\s/g,'').toLowerCase();
const aliases:any={subjectName:['과목명','교과목','과목'],subjectGroup:['교과군','교과','영역'],curriculumCategory:['교육과정분류','과목분류','선택과목분류'],schoolRequirement:['학교운영','필수선택','필수여부'],targetGrade:['대상학년','이수학년','신청대상학년'],targetSemester:['대상학기','이수학기','학기'],selectionGroup:['선택군','과목군'],selectionCount:['선택가능개수','선택개수'],credit:['학점','이수단위','단위'],timing:['이수시기','개설시기'],selectionConditions:['선택조건','선택안내'],concurrentLimit:['동시선택제한','선택제한'],prerequisite:['선수과목','선이수'],subsequent:['후속과목','후속']};
const column=(headers:string[],name:string)=>headers.findIndex(header=>aliases[name].some((alias:string)=>key(header).includes(key(alias))));
const value=(cells:string[],index:number)=>index<0?'':clean(cells[index]||'');
const category=(value:string)=>/공통/.test(value)?'common':/진로/.test(value)?'career':/융합/.test(value)?'convergence':/일반/.test(value)?'general':'';

export async function parseSchoolBookHwpx(file:File){
  const zip=await JSZip.loadAsync(await file.arrayBuffer()); const sections=Object.keys(zip.files).filter(name=>/^Contents\/section\d+\.xml$/i.test(name)); const rows:SchoolBookRow[]=[]; let tableCount=0; let paragraphCount=0;
  for(const path of sections){const xml=await zip.file(path)?.async('text');if(!xml)continue;const document=new DOMParser().parseFromString(xml,'application/xml');paragraphCount+=document.getElementsByTagNameNS('*','p').length;const tables=[...document.getElementsByTagNameNS('*','tbl')];for(const [tableIndex,table] of tables.entries()){tableCount++;const rawRows=[...table.getElementsByTagNameNS('*','tr')].map((row:any)=>[...row.getElementsByTagNameNS('*','tc')].map((cell:any)=>clean(cell.textContent||''))).filter(cells=>cells.some(Boolean));if(rawRows.length<2)continue;const headers=rawRows[0];const courseIndex=column(headers,'subjectName');if(courseIndex<0)continue;const indexes=Object.fromEntries(Object.keys(aliases).map(name=>[name,column(headers,name)]));for(const cells of rawRows.slice(1)){const subjectName=value(cells,courseIndex);if(!subjectName||/^(합계|계|비고|구분)$/.test(subjectName))continue;const rawCategory=value(cells,indexes.curriculumCategory);const rawRequirement=value(cells,indexes.schoolRequirement);rows.push({subjectName,subjectGroup:value(cells,indexes.subjectGroup),curriculumCategory:category(rawCategory)||rawCategory,schoolRequirement:/필수/.test(rawRequirement)?'required':'optional',targetGrade:value(cells,indexes.targetGrade),targetSemester:value(cells,indexes.targetSemester),selectionGroup:value(cells,indexes.selectionGroup),selectionCount:value(cells,indexes.selectionCount),credit:value(cells,indexes.credit),timing:value(cells,indexes.timing),selectionConditions:value(cells,indexes.selectionConditions),concurrentLimit:value(cells,indexes.concurrentLimit),prerequisite:value(cells,indexes.prerequisite),subsequent:value(cells,indexes.subsequent),sourceLocation:`${path} 표 ${tableIndex+1}`,adminNote:'',csatPriority:false,humanitiesPriority:false,sciencePriority:false});}}}
  return {rows,summary:{sectionCount:sections.length,tableCount,paragraphCount,recognizedCount:rows.length,needsConfirmation:rows.filter(row=>!row.subjectGroup||!row.curriculumCategory).length}};
}
